name: AntaresCommandBlocks
main: kloudy.main.AntaresCommandBlocks
version: 1.1
author: Kloudy

permissions:
  acb.set:
    description: Allows a player to set a command in a command block with a book
    default: op